name: Build and Publish Images

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - variant: bookworm
            context: debian/bookworm
            dockerfile: debian/bookworm/Dockerfile
          - variant: trixie
            context: debian/trixie
            dockerfile: debian/trixie/Dockerfile
          - variant: forky
            context: debian/forky
            dockerfile: debian/forky/Dockerfile
          - variant: jammy
            context: ubuntu/jammy
            dockerfile: ubuntu/jammy/Dockerfile
          - variant: noble
            context: ubuntu/noble
            dockerfile: ubuntu/noble/Dockerfile
    env:
      IMAGE_NAME: vitexsoftware/multiflexi-${{ matrix.variant }}
      REPO_URL: https://repo.multiflexi.eu
      KEY_URL: https://repo.multiflexi.eu/KEY.gpg
      PLATFORMS: linux/amd64,linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ env.PLATFORMS }}
          push: true
          build-args: |
            REPO_URL=${{ env.REPO_URL }}
            KEY_URL=${{ env.KEY_URL }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest

